module.exports =
  "COFFEE": "text/javascript",
  "LESS": "text/css",
  "CSS": "text/css",
  "GIF": "image/gif",
  "HTML": "text/html",
  "ICO": "image/x-icon",
  "JPEG": "image/jpeg",
  "JPG": "image/jpeg",
  "JS": "text/javascript",
  "JSON": "application/json",
  "PDF": "application/pdf",
  "PNG": "image/png",
  "SVG": "image/svg+xml",
  "SWF": "application/x-shockwave-flash",
  "TIFF": "image/tiff",
  "TXT": "text/plain",
  "WAV": "audio/x-wav",
  "WMA": "audio/x-ms-wma",
  "WMV": "video/x-ms-wmv",
  "XML": "text/xml",
  "HTML":"text/html",
  "FORM":"application/x-www-form-urlencoded"